# Generated by Django 3.1 on 2020-08-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='security_a',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='security_q',
            field=models.CharField(choices=[('1', 'What is your birthdate'), ('2', 'What is your old phone number'), ('3', 'What is your PET name')], max_length=244, null=True),
        ),
    ]
